# enums.gd
extends Node

enum ItemType { NONE, APPLE, BREAD, CABBAGE, CARROT, DOUGH, FLOUR, EGG, ONION, PUMPKIN, PEPPER, MILK, TOMATO, WHEAT, INVENTORY_UPGRADE }

enum NPCType { MAYOR, MERCHANT_1, MERCHANT_2, MERCHANT_3, WIZARD, GUARD }

enum State { IDLE, WALK, ATTACK1, ATTACK2, ATTACK3, HURT, DEATH }

enum CoinType { REAL }
